Refactor selectedValue prop closes #107
Matteas-Eden/roll-for-reaction pull request #108
Opened 2020-04-11 03:41 UTC by Matteas-Eden

Changes selection value to depend on any conditional as opposed to
simply matching the title.

GitHub Issue (If applicable): #107 

## PR Type

What kind of change does this PR introduce?

- Enhancement

## What is the current behavior?

`<SelectedButton />` becomes 'selected' based on `selectedValue` matching the `title`.

## What is the new behavior?

`<SelectedButton />` becomes 'selected' based on `true` value of `selected` prop.

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] Tested code with current upstream repo
- [ ] Added new tests to the test suite for the feature
- [x] Tested the full test suite, and ensured that the feature does not break current build.
- [ ] Docs have been added/updated which fit (for bug fixes / features)
- [x] Contains **NO** breaking changes
- [x] Associated with an issue (GitHub or internal)
- [ ] Checked licensing of Frameworks/Libraries (if applicable)

## Other information

Internal Issue (If applicable): Closes #107

2020-04-11 10:24 UTC, Pyxxil requested changes
Looks good!

I do have one question (which is not major, just more of a curiosity -- and doesn't necessarily require the request changes, but that's more because I'd like an answer): Would you reckon it'd be a good idea to turn these into Group Select Buttons? I think it could look rather nice for something like our Character Class/Race Buttons, something like:

<SelectButtonGroup group=["Human", "Elf", "Dwarf"] select={(value) => value == currentRace; } onClick={setRace}   />

Which would then populate all of our SelectButtons for us?

2020-04-11 12:11 UTC, KimberleyEvans-Parker requested changes
The reason I had it passed in as selected value originally was so that outside of that, if you wanted to change it, you would only have to change it in one place.  Now it has to be changed in two places, which I prefer less.  Perhaps Josh's suggestion of making another component for the group of select buttons is best, because then you would only need to change something in one place.

2020-04-12 22:21 UTC, Pyxxil approved these changes
Looks much nicer.

2020-04-13 07:02 UTC, KimberleyEvans-Parker approved these changes
That looks nicer.  Just a point for future, though; if you pass more than three items in, it starts to look pretty bad and some buttons can't be reached.  There ought to be a new line every 3 buttons or so.  
![image](https://user-images.githubusercontent.com/45865186/79099918-4d729c80-7db9-11ea-8d5d-a0a5a38f6c0e.png)

2020-04-13 11:58 UTC, merged