Hide buttons at 0 ability points
Matteas-Eden/roll-for-reaction pull request #157
Opened 2020-04-25 03:42 UTC by Frosty273

GitHub Issue (If applicable): #151 

## PR Type

What kind of change does this PR introduce?
- Feature

## What is the current behavior?
The buttons to increment and decrement an ability still remain even if the player has no more ability points to invest. 

## What is the new behavior?
Increment and decrement buttons are hidden when a player has no ability points.

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] Tested code with current upstream repo
- [ ] Added new tests to the test suite for the feature
- [ ] Tested the full test suite, and ensured that the feature does not break current build.
- [ ] Docs have been added/updated which fit (for bug fixes / features)
- [x] Contains **NO** breaking changes
- [x] Associated with an issue (GitHub or internal)
- [ ] Checked licensing of Frameworks/Libraries (if applicable) 

## Other information

Internal Issue (If applicable):

Closes #151

2020-04-25 04:03 UTC, Matteas-Eden requested changes
It looks good, but there is a glaring issue for when you first start the game. If you spend all your ability points, you are supposed to be able to then *decrease* the ability scores. This is no longer possible, since the buttons vanish. 

So, they should only become hidden when you don't have ability points available to spend upon opening the dialog.

2020-04-25 12:48 UTC, Pyxxil requested changes
Testing locally, the increment/decrement buttons don't seem to change at all for some reason... I've left a couple of thoughts on what worked for me.

2020-04-25 12:48 UTC, Pyxxil commented on src/components/ability/index.js
> +                                : 'visible',
Shouldn't this be 'value === minValue'?

2020-04-25 12:48 UTC, Pyxxil commented on src/components/ability/index.js
> +                                : 'visible',
Shouldn't this be 'points === 0 || value === MAX_ABILITY_SCORE'?

2020-04-27 04:24 UTC, Matteas-Eden approved these changes
LGTM, nice work @Frosty273!

2020-04-27 04:38 UTC, Pyxxil approved these changes
Looks good!

2020-04-27 04:38 UTC, merged