Initial Implementation of Spellcasting System
Matteas-Eden/roll-for-reaction pull request #160
Opened 2020-04-25 04:49 UTC by Pyxxil

GitHub Issue (If applicable): #153 

## PR Type

What kind of change does this PR introduce?
- Feature

## What is the current behavior?
The player is not able to cast spells.

## What is the new behavior?
The player is able to select a spell using the Spellbook Dialog (press 'b'), and cast said spell using 'c'.

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] Tested code with current upstream repo
- [ ] Added new tests to the test suite for the feature
- [ ] Tested the full test suite, and ensured that the feature does not break current build.
- [ ] Docs have been added/updated which fit (for bug fixes / features)
- [x] Contains **NO** breaking changes
- [x] Associated with an issue (GitHub or internal)
- [ ] Checked licensing of Frameworks/Libraries (if applicable) 

## Other information
Details still to flesh out:
 - Spells (number, costs(mana), how to unlock, damage/heal, sprites, etc)
 - Spellbook
    - Add sprites to dialog
    - Ability to look at spells
       - Give some information similar to when viewing an item in inventory
 - Display active spell somewhere?
 - Probably more

You will need to re-run 'yarn install' to actually run the branch, as I added a dependency so that I can programmatically change keyframes (don't ask...) 

Internal Issue (If applicable): closes #153

2020-04-25 09:14 UTC, Matteas-Eden reviewed
I didn't mention it in the original issue, but I'm wondering if we should also add some mana regeneration. We planned it, but I forgot to put it in the issue. How do you feel about including it in this PR? It just seems a little strange to give the player spells but not allow them to get mana back in a meaningful way.

2020-04-25 09:58 UTC, Pyxxil commented
> I didn't mention it in the original issue, but I'm wondering if we should also add some mana regeneration. We planned it, but I forgot to put it in the issue. How do you feel about including it in this PR? It just seems a little strange to give the player spells but not allow them to get mana back in a meaningful way.

Hence why I brought up adding mana potions (in chat, not here).

2020-04-25 11:21 UTC, Matteas-Eden requested changes
The PR is really good, there's no doubt about that. I would appreciate if you can adjust the spacing in the spellbook, because right now they're so close that the borders seem to overlap.

2020-04-25 11:21 UTC, Matteas-Eden commented on src/features/player/reducer.js
> +import Mend from '../../data/spells/mend';
This is unused, and produces a warning.

2020-04-25 11:21 UTC, Matteas-Eden commented on src/features/journal/reducer.js
> +const correctGrammar = word => {
Although I don't really have issues with the implementation of the function (you could probably use `lower()` to reduce the number of cases though), I think the name is a little misleading. It determines the indefinite article, which isn't really correcting grammar. I think it could be renamed to something like *getIndefiniteArticle* (it's not a great name, but at least it's accurate).

2020-04-25 11:28 UTC, Pyxxil commented on src/features/journal/reducer.js
> +const correctGrammar = word => {
I've removed it, it's been replaced with an 'a(n)' where it's used.

2020-04-27 11:45 UTC, Matteas-Eden approved these changes
I think this is good enough to be merged, although I will make a small list of improvements here (all of which are likely to be future issues).

**Improvements**
- Add more spells
- Unlock spells as a player levels up
- Display active spell in UI
- Add information about spell to spellbook
- Add method to restore mana

2020-04-27 11:45 UTC, merged