Add a lower limit to sell price fixes #167
Matteas-Eden/roll-for-reaction pull request #169
Opened 2020-04-26 11:05 UTC by Matteas-Eden

GitHub Issue (If applicable): #167 

## PR Type

What kind of change does this PR introduce?

- Bugfix

## What is the current behavior?

A player who has 0 Charisma sells items for 0 gold.

## What is the new behavior?

If the sell price of an item is calculated to be 0 (or below, although not currently possible), then that value for the sell price is discarded and instead the sell price is 5% of the base price.

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] Tested code with current upstream repo
- [ ] Added new tests to the test suite for the feature
- [ ] Tested the full test suite, and ensured that the feature does not break current build.
- [x] Docs have been added/updated which fit (for bug fixes / features)
- [x] Contains **NO** breaking changes
- [x] Associated with an issue (GitHub or internal)
- [ ] Checked licensing of Frameworks/Libraries (if applicable) 

## Other information

Internal Issue (If applicable): Closes #167.

2020-04-28 11:05 UTC, KimberleyEvans-Parker requested changes
Works great :D just fix the comments please

2020-04-28 11:05 UTC, KimberleyEvans-Parker commented on src/utils/calculate-prices.js
> +//  max: maximum percentage of base price that item can be bought for
I think these comments are outdated

2020-04-29 11:55 UTC, Pyxxil requested changes
Note that, as #180 was closed before this, we will also need to update how we retrieve the sell price for the item being viewed (src/components/view-item/index.js line 195)

2020-04-29 23:02 UTC, KimberleyEvans-Parker submitted a review, later dismissed
seems to work well for me :)

2020-04-30 11:25 UTC, Pyxxil approved these changes
Looks fine

2020-04-30 11:26 UTC, merged