Implement Mana Regeneration
Matteas-Eden/roll-for-reaction pull request #175
Opened 2020-04-27 23:05 UTC by Pyxxil

GitHub Issue (If applicable): #174 

## PR Type

What kind of change does this PR introduce?
- Feature

## What is the current behavior?
The only way to get more mana after you have used it all is to level up.

## What is the new behavior?
Mana potions are available in the shop, and the player will also passively regain mana when out of combat.

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] Tested code with current upstream repo
- [ ] Added new tests to the test suite for the feature
- [ ] Tested the full test suite, and ensured that the feature does not break current build.
- [ ] Docs have been added/updated which fit (for bug fixes / features)
- [x] Contains **NO** breaking changes
- [x] Associated with an issue (GitHub or internal)
- [ ] Checked licensing of Frameworks/Libraries (if applicable) 

## Other information
This isn't set in stone -- currently the player has to be out of combat for 10 turns (and every 10 out of combat turns thereafter) to regen 1 mana passively. I think this really should instead be relative to the amount they would regenerate with a potion (not entirely sure the amount at the moment).

I'd also like to add the active spell to the UI in this PR (which I'll also make an onscreen button so that Mobile Users can press that to cast their spell).

Internal Issue (If applicable): closes #174

2020-04-30 05:38 UTC, Pyxxil commented
This should be merged after #181, so that we can avoid any issues regarding some refactoring.

2020-05-02 07:41 UTC, Pyxxil commented on src/data/items/potions/great-hp-potion/index.js
> +    kind: 'mana',
This should probably be 'health'

2020-05-03 02:12 UTC, Matteas-Eden requested changes
There don't seem to be any mana potions available until level 10. Could you add `Mana Potion` and `Greater Mana Potion` to the first shop tier?

2020-05-03 02:12 UTC, Matteas-Eden commented on src/components/view-item/index.js
> +                acceptText={data.kind == 'health' ? 'Heal' : 'Restore'}
Should be `===` instead of `==`.

2020-05-03 18:00 UTC, Matteas-Eden requested changes
In addition to the conflict with `master` that needs to be resolved, I also get an issue with having a defence value of `NaN`. Perhaps that won't persist if this gets merged, but I'd like some confirmation that it won't produce an issue before I approve.

2020-05-03 21:22 UTC, Pyxxil commented
> In addition to the conflict with `master` that needs to be resolved, I also get an issue with having a defence value of `NaN`. Perhaps that won't persist if this gets merged, but I'd like some confirmation that it won't produce an issue before I approve.

I can't reproduce this, and even if so, it wasn't introduced as an issue by this PR and probably should have been caught in a seperate issue.

2020-05-04 02:18 UTC, Matteas-Eden approved these changes
The previous error I mentioned was a run-time error due to my own testing setup, so apologies for that. LGTM.

2020-05-04 02:43 UTC, merged