Add Mana Cost to Spell View
Matteas-Eden/roll-for-reaction pull request #210
Opened 2020-05-07 11:40 UTC by Pyxxil

GitHub Issue (If applicable): #206

## PR Type

What kind of change does this PR introduce?
- Feature
- Code style update (formatting)

## What is the current behavior?
The mana cost of spells is not displayed to the user, and the colours of some items when viewing them in the inventory, shop, or entries in the journal were difficult to read.

## What is the new behavior?
Mana cost is displayed for the user when they view the spell in the spellbook, and the colour for --purple was slightly modified.

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] Tested code with current upstream repo
- [ ] Added new tests to the test suite for the feature
- [ ] Tested the full test suite, and ensured that the feature does not break current build.
- [ ] Docs have been added/updated which fit (for bug fixes / features)
- [x] Contains **NO** breaking changes
- [x] Associated with an issue (GitHub or internal)
- [ ] Checked licensing of Frameworks/Libraries (if applicable) 

Internal Issue (If applicable): closes #206

2020-05-07 13:27 UTC, Matteas-Eden requested changes
Could you change `mana cost` to `mana-cost`?

2020-05-07 22:31 UTC, Pyxxil commented
> Could you change `mana cost` to `mana-cost`?

Would you mind giving a reason for why this would be necessary?

2020-05-08 00:57 UTC, Matteas-Eden commented
> 
> 
> > Could you change `mana cost` to `mana-cost`?
> 
> Would you mind giving a reason for why this would be necessary?

I just felt that we should avoid the use of spaces in strings where possible in favour of separators, such as `-`. I'm tempted to mention Unix guidelines for filenames and liken it to how spaces should be avoided wherever possible, but I understand that such a comparison is a bit of a stretch. I suppose I just feel that since it's acting as a key, it shouldn't have a space in it.

2020-05-08 01:15 UTC, Pyxxil commented
> I just felt that we should avoid the use of spaces in strings where possible in favour of separators, such as -. I'm tempted to mention Unix guidelines for filenames and liken it to how spaces should be avoided wherever possible, but I understand that such a comparison is a bit of a stretch. I suppose I just feel that since it's acting as a key, it shouldn't have a space in it.

Yes I'd agree that's quite a stretch, and kind of goes against the normal convention for the entire project (which is arguably more important).

Also, it's not used as a 'key', assuming you mean in the sense that it's the property in the object -- it's not (the code should easily show that, hence why I air-quoted key: I assume you've read the code and are aware of what's going on). It's only used for the display, and internally is held as 'manaCost' as the property name, which is what I would have thought you'd be referring to.

So, an elaboration on what you mean by 'key' would be appreciated.

2020-05-08 03:03 UTC, Matteas-Eden commented
> Yes I'd agree that's quite a stretch, and kind of goes against the normal convention for the entire project (which is arguably more important).
> 
> Also, it's not used as a 'key', assuming you mean in the sense that it's the property in the object -- it's not (the code should easily show that, hence why I air-quoted key: I assume you've read the code and are aware of what's going on). It's only used for the display, and internally is held as 'manaCost' as the property name, which is what I would have thought you'd be referring to.
> 
> So, an elaboration on what you mean by 'key' would be appreciated.

My apologies for the irresponsible use of the term 'key'. Perhaps 'flag' would a better descriptor, although that tends to refer to boolean variables, so it wouldn't really work here. 

In any case, the point you raise about the project-wide convention is more important. Consider the change request redacted.

2020-05-08 03:03 UTC, Matteas-Eden approved these changes

2020-05-08 03:04 UTC, merged