Logo in Readme
Matteas-Eden/roll-for-reaction pull request #31
Opened 2020-03-22 01:01 UTC by KimberleyEvans-Parker

GitHub Issue (If applicable): #21 

## PR Type

What kind of change does this PR introduce?
- Documentation content changes

## What is the current behaviour?
Readme has no logo

## What is the new behaviour?
Readme has 'Roll for Reaction's logo

## PR Checklist

Please check if your PR fulfills the following requirements:

- [ ] Tested code with current upstream repo
- [ ] Added new tests to the test suite for the feature
- [ ] Tested the full test suite, and ensured that the feature does not break current build.
- [ ] Docs have been added/updated which fit (for bug fixes / features)
- [x] Contains **NO** breaking changes
- [x] Associated with an issue (GitHub or internal)
- [ ] Checked licensing of Frameworks/Libraries (if applicable) 

## Other information

Internal Issue (If applicable):
closes #21

2020-03-22 01:56 UTC, Matteas-Eden requested changes
Looks good, but I've left some feedback I'd like you to look at.

2020-03-22 01:56 UTC, Matteas-Eden commented on README.md
> +
I'd prefer it if we used a link that isn't subject to change, like the one posted in a comment on the issue.

`![logo](https://user-images.githubusercontent.com/45865186/77014224-a9265180-69d6-11ea-92d3-18af1d76c740.png)`

2020-03-22 01:56 UTC, Matteas-Eden commented on README.md
>  # Roll For Reaction
If we have the logo (which contains the title of the project), I don't think this heading is necessary anymore.

2020-03-23 21:22 UTC, Pyxxil submitted a review, later dismissed

2020-03-23 21:22 UTC, Pyxxil commented on README.md
> +
Why are we not using relative links? This is the recommended way to do images in markdown.

2020-03-24 01:15 UTC, Matteas-Eden submitted a review, later dismissed
LGTM, thanks for addressing my feedback.

2020-03-24 01:50 UTC, Matteas-Eden requested changes
Left some feedback in accordance with discussion on Messenger.

2020-03-24 01:50 UTC, Matteas-Eden commented on README.md
> +<img src="https://user-images.githubusercontent.com/45865186/77014224-a9265180-69d6-11ea-92d3-18af1d76c740.png" width="400">
Change to use relative link to wider image:
`<img src="public/logo-wide.png"`

2020-03-24 02:17 UTC, Matteas-Eden approved these changes
It's... *beautiful*.

2020-03-24 02:17 UTC, merged