Bug/floor
Matteas-Eden/roll-for-reaction pull request #345
Opened 2020-08-10 07:26 UTC by Frosty273

GitHub Issue (If applicable): #344 

## PR Type

What kind of change does this PR introduce?

## What is the current behavior?
Can't enter floor 4-5

## What is the new behavior?

Can enter floor 4-5

## PR Checklist

Please check if your PR fulfills the following requirements:

- [x] Tested code with current upstream repo
- [] Added new tests to the test suite for the feature
- [ ] Tested the full test suite, and ensured that the feature does not break current build.
- [ ] Docs have been added/updated which fit (for bug fixes / features)
- [x] Contains **NO** breaking changes
- [x] Associated with an issue (GitHub or internal)
- [ ] Checked licensing of Frameworks/Libraries (if applicable) 

## Other information

Internal Issue (If applicable):

2020-08-10 12:24 UTC, Matteas-Eden commented
Do you mind linking the issue this resolves?

2020-08-11 04:54 UTC, Pyxxil requested changes

2020-08-11 04:54 UTC, Pyxxil commented on src/data/monsters/index.js
> +    'lich king': LicKing,
How come this was changed to “LicKing”? Did you remove the ‘h’ that was here for a reason?

2020-08-12 08:16 UTC, Pyxxil approved these changes
Looks great!

2020-08-12 08:16 UTC, merged